### ISSUE TITLE
已经安装mpg123模块，播放节目时仍然出现“ FileNotFoundError: [Errno 2] No such file or directory: 'mpg123' ”异常 

### ISSUE THREAD

**Issue by NamelessAshone** [yihong0618/gaycore#1]
Gay核的朋友：
     您好，我尝试使用gaycore来收听节目，但是遇到了一些麻烦：
     当我根据错误提示安装了mpg123模块后，再次播放节目时，程序抛出了相同的错误，详细错误提示附在下方。

Best wishes
ShuShuXin

错误信息：
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gaycore/player.py", line 17, in run_mpg123
    para, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'mpg123'

**Comment by yihong0618** [comment]
你终端输入下mpg123看是否成功安装。

**Comment by NamelessAshone** [comment]
感谢回复！
找到原因了，我用pip装的mpg123，得使用apt安装mpg123。

**Comment by yihong0618** [comment]
客气～
