### ISSUE TITLE
在树莓派3上运行不正常，输出结果如下

### ISSUE THREAD

**Issue by Adiwon** [yihong0618/gaycore#3]
`Traceback (most recent call last):
                                    File "/usr/local/bin/gaycore", line 10, in <module>
                                                                                           sys.exit(run())
                                                                                                            File "/usr/local/lib/python3.5/dist-packages/gaycore/main.py", line 6, in run
                                                              gcore_box = GcoreBox()
                                                                                      File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 52, in __init__
                                                   self._init_curses()
                                                                        File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 61, in _init_curses
                                         curses.init_pair(1, curses.COLOR_BLACK, 197) # 接近机核主题的颜色
                                                                                                          _curses.error: init_pair() returned ERR
                  pi@raspberrypi:~ $
`

**Comment by Adiwon** [comment]
原输出就是这样

**Comment by yihong0618** [comment]
树莓派应该不支持这个主题色号，你把197改成curses.COLOR_BLUE试试之后我会修复这块

**Comment by Adiwon** [comment]
> 树莓派应该不支持这个主题色号，你把197改成curses.COLOR_BLUE试试之后我会修复这块

辛苦了，修改之后没什么变化，输出是这样的：
`Traceback (most recent call last):
                                    File "/usr/local/bin/gaycore", line 10, in <module>
                                                                                           sys.exit(run())
                                                                                                            File "/usr/local/lib/python3.5/dist-packages/gaycore/main.py", line 6, in run
                                                              gcore_box = GcoreBox()
                                                                                      File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 52, in __init__
                                                   self._init_curses()
                                                                        File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 61, in _init_curses
                                         curses.init_pair(1, curses.COLOR_BLUE, 197) # 接近机核主题的颜色
                                                                                                         _curses.error: init_pair() returned ERR
`

**Comment by yihong0618** [comment]
你应该改197 不是 curses.COLOR_BLACK

**Comment by yihong0618** [comment]
curses.init_pair(1, curses.COLOR_BLACK , curses.COLOR_BLUE) 这样看看可以么

**Comment by Adiwon** [comment]
修改后程序可以打开了，但一播放节目就会报错，输出是这样：
`Exception in thread Thread-1:
                             Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
 self._target(*self._args, **self._kwargs) 
File "/usr/local/lib/python3.5/dist-packages/gaycore/player.py", line 21, in run_mpg123
 self.popen_handler.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe 
`
这些东西覆盖在电台界面之上，电台界面此时还可以操作，如果再按空格键播放/暂停，就会继续输出这些然后崩掉：
`self.pick(self.boxes)
File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 329, in pick 
self.mainloop()
File "/usr/local/lib/python3.5/dist-packages/gaycore/gcore_box.py", line 259, in mainloop 
 self.player.pause_or_resume_mp3()
File "/usr/local/lib/python3.5/dist-packages/gaycore/player.py", line 49, in pause_or_resume_mp3
self.popen_handler.stdin.flush()
 BrokenPipeError: [Errno 32] Broken pipe
`
我分行分的不一定正确，因为原输出实在没法复制粘贴，和界面字符混合在一起贴过来就乱掉了
<img width="830" alt="default" src="https://user-images.githubusercontent.com/16150302/53411184-cf123a00-3a00-11e9-9086-6979a5c52dc6.PNG">

**Comment by Adiwon** [comment]
更新：没事了……重装了一遍mpg123就可以正常使用了，谢谢机友！

**Comment by yihong0618** [comment]
不客气，欢迎随时提建议
